### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

### ISSUE THREAD

**Issue by andremarceloteixeira** [aerisweather/node-deploy-lambda-function#2]
Hey,
I get the next error....

> ./node_modules/.bin/deploy-lambda-function

 -c ./calculator-service-lambda/deploy/params.test.json
+ ./node_modules/.bin/deploy-lambda-function -c ./calculator-service-lambda/deploy/params.test.json
Removing devDependencies....
(keeping previous node_modules at /node_modules.bak, will restore later)
npm WARN microservices@0.0.1 No repository field.
npm WARN microservices@0.0.1 No license field.
Removing devDependencies... complete!
Archiving lambda function code....
Archiving lambda function code (11.28MiB).... complete!
Restoring previous node_modules...
Restoring previous node_modules... complete!
Updating lambda function code...
Updating lambda function code... complete!
Updating function configuration...
Error: Failed to load env from s3://node-js-configurations/env/test.env: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/@aerisweather/deploy-lambda-function/dist/util/loadS3Env.js:58:27)
    at step (/opt/atlassian/pipelines/agent/build/node_modules/@aerisweather/deploy-lambda-function/dist/util/loadS3Env.js:32:23)
    at Object.throw (/opt/atlassian/pipelines/agent/build/node_modules/@aerisweather/deploy-lambda-function/dist/util/loadS3Env.js:13:53)
    at rejected (/opt/atlassian/pipelines/agent/build/node_modules/@aerisweather/deploy-lambda-function/dist/util/loadS3Env.js:5:65)
    at process._tickDomainCallback (node.js:407:9)

**Comment by andremarceloteixeira** [comment]
https://github.com/aws/aws-sdk-js/issues/829

**Comment by andremarceloteixeira** [comment]
But not possible i change, because i get the module via NPM install in my deploy process!

**Comment by andremarceloteixeira** [comment]
Create new bucket in the diferent region is Solved!
But the code is not prepared for running in the some AWS regions!!! For example Frankfurt

**Comment by four43** [comment]
Hey @andremarceloteixeira - Glad to hear you got it working! 

We haven't tried using this code to deploy to functions outside of us-east-1. Were you trying to use resources across regions? I'm curious if there is some issue there. We are just using the aws-sdk under the hood so in theory it should work fine, but maybe we need some more specific config somewhere.

Thanks,
-Seth

**Comment by andremarceloteixeira** [comment]
Hello @four43 .
yes but no problem. I create one bucket in us-east-1, and upload S3 file configuration and is OK! 
See : https://github.com/aws/aws-sdk-js/issues/829
Thanks for the package  it is very useful.
Best
marcelo
